#!/usr/bin/env python3

"""Mexican state codes (project-internal) mapped to their full names."""

MX_STATES: dict[str, str] = {
    "AGU": "Aguascalientes",
    "BCA": "Baja California",
    "BCS": "Baja California Sur",
    "CAM": "Campeche",
    "CHH": "Chihuahua",
    "CHI": "Chiapas",
    "CMX": "Ciudad de México",
    "COA": "Coahuila",
    "COL": "Colima",
    "DUR": "Durango",
    "GUA": "Guanajuato",
    "GRO": "Guerrero",
    "HID": "Hidalgo",
    "JAL": "Jalisco",
    "MEX": "Estado de México",
    "MIC": "Michoacán",
    "MOR": "Morelos",
    "NAY": "Nayarit",
    "NLE": "Nuevo León",
    "OAX": "Oaxaca",
    "PUE": "Puebla",
    "QUE": "Queretaro",
    "ROO": "Quintana Roo",
    "SIN": "Sinaloa",
    "SLP": "San Luis Potosi",
    "SON": "Sonora",
    "TAB": "Tabasco",
    "TAM": "Tamaulipas",
    "TLA": "Tlaxcala",
    "VER": "Veracruz",
    "YUC": "Yucatan",
    "ZAC": "Zacatecas",
}
